do $$ declare u uuid;f uuid;pid uuid;points integer;begin
 select id into u from profiles where approval_status='approved' order by id limit 1;
 select fx.id into f from fixtures fx join rounds r on r.id=fx.round_id join seasons s on s.id=r.season_id where s.season_code='GULF-27-2026' and r.round_number=4 order by fx.id limit 1;
 update fixtures set status='finished' where id=f;
 insert into predictions(fixture_id,user_id,outcome,predicted_home_score,predicted_away_score,finish_method) values(f,u,'home',1,1,'penalties') on conflict(fixture_id,user_id) do update set outcome='home',predicted_home_score=1,predicted_away_score=1,finish_method='penalties' returning id into pid;
 insert into gulf_knockout_results(fixture_id,winner,finish_method,home_score,away_score) values(f,'home','penalties',1,1);
 select total_points into points from prediction_scores where prediction_id=pid;
 if points<>5 then raise exception 'Expected five points, got %',points;end if;
 update gulf_knockout_results set winner='away' where fixture_id=f;
 select total_points into points from prediction_scores where prediction_id=pid;
 if points<>4 then raise exception 'Expected independent exact/method bonuses';end if;
 update gulf_knockout_results set winner='home',finish_method='extra_time',home_score=2,away_score=1 where fixture_id=f;
 select total_points into points from prediction_scores where prediction_id=pid;
 if points<>1 then raise exception 'Expected winner point only';end if;
 update gulf_knockout_results set winner='away',finish_method='regulation',home_score=0,away_score=1 where fixture_id=f;
 select total_points into points from prediction_scores where prediction_id=pid;
 if points<>0 then raise exception 'Expected zero for wrong predictions';end if;
 begin update predictions set outcome='draw' where id=pid;raise exception 'DRAW_ACCEPTED';exception when others then if sqlerrm='DRAW_ACCEPTED' then raise;end if;end;
 begin update predictions set predicted_home_score=2 where id=pid;raise exception 'INVALID_PENALTY_SCORE_ACCEPTED';exception when others then if sqlerrm='INVALID_PENALTY_SCORE_ACCEPTED' then raise;end if;end;
end $$;
