import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const patch=html.match(/<script id="gulf27-semifinal-view">([\s\S]*?)<\/script>/)[1];
const fn=patch.match(/const locked=\(\)=>[^;]+;/)[0];
const context={Date:class extends Date{static now(){return Date.parse('2026-10-01T17:30:00Z')}},currentRound:{first_match_at:'2026-10-03T15:55:00Z',predictions_close_at:'2026-10-03T14:55:00Z'}};
vm.createContext(context);vm.runInContext(fn+'globalThis.result=locked()',context);assert.equal(context.result,false,'semifinal predictions open now without waiting for 48h window');
assert.match(patch,/بونص النتيجة الدقيقة/);
console.log('PASS: knockout predictions open now and labeled exact-score bonus');
